
$path = "D:\Programs\Web Development\Expense Tracker App\client\src\pages\Groups\Groups.jsx"

$lines = @(
'import React, { useState, useEffect, useContext } from "react";',
'import { FaPlus, FaTrash, FaArrowRight, FaTimes, FaUserPlus, FaReceipt } from "react-icons/fa";',
'import { GroupContext } from "../../context/GroupContext";',
'import { AuthContext } from "../../context/AuthContext";',
'import ReceiptScanner from "../../components/receipt/ReceiptScanner";',
'',
'const GROUP_ICONS = ["👥","✈️","🏠","🍕","🎉","🏖️","💼","🎓","🏋️","🚗"];',
'const CATEGORIES = ["Food","Travel","Utilities","Entertainment","Shopping","Health","Rent","General"];',
'',
'const fmt = (n, cur = "INR") => {',
'  const s = cur === "INR" ? "₹" : cur === "EUR" ? "€" : cur === "GBP" ? "£" : "$";',
'  return s + Number(n).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });',
'};',
'',
'// ─── AddExpenseModal ───────────────────────────────────────────────────────',
'const AddExpenseModal = ({ group, onAdd, onClose }) => {',
'  const { user } = useContext(AuthContext);',
'  const [form, setForm] = useState({',
'    description: "", amount: "", category: "Food",',
'    date: new Date().toISOString().split("T")[0],',
'    paidByUserId: user?._id || "",',
'  });',
'  const [err, setErr] = useState("");',
'  const f = (k) => (e) => setForm((p) => ({ ...p, [k]: e.target.value }));',
'  const handleSubmit = async (e) => {',
'    e.preventDefault();',
'    if (!form.description || !form.amount) { setErr("Description and amount are required."); return; }',
'    const res = await onAdd({ ...form, amount: parseFloat(form.amount) });',
'    if (res.success) onClose();',
'    else setErr(res.error);',
'  };',
'  const cls = "w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 focus:border-indigo-500 rounded-xl px-4 py-2.5 text-sm outline-none transition";',
'  return (',
'    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 backdrop-blur-sm p-4">',
'      <div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-slate-200 dark:border-slate-800 animate-fade-in">',
'        <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">',
'          <h3 className="font-bold text-slate-800 dark:text-slate-100">Add Group Expense</h3>',
'          <button onClick={onClose} className="text-slate-400 hover:text-slate-600"><FaTimes size={16} /></button>',
'        </div>',
'        <form onSubmit={handleSubmit} className="p-6 space-y-4">',
'          {err && <p className="text-xs text-rose-500 bg-rose-50 dark:bg-rose-950/30 border border-rose-100 dark:border-rose-900/30 px-3 py-2 rounded-xl">{err}</p>}',
'          <div><label className="text-xs text-slate-400 block mb-1">Description</label>',
'            <input className={cls} value={form.description} onChange={f("description")} placeholder="Dinner, Hotel..." required /></div>',
'          <div className="grid grid-cols-2 gap-4">',
'            <div><label className="text-xs text-slate-400 block mb-1">Amount (₹)</label>',
'              <input type="number" step="0.01" min="0" className={cls} value={form.amount} onChange={f("amount")} required /></div>',
'            <div><label className="text-xs text-slate-400 block mb-1">Category</label>',
'              <select className={cls} value={form.category} onChange={f("category")}>{CATEGORIES.map((c) => <option key={c}>{c}</option>)}</select></div>',
'          </div>',
'          <div className="grid grid-cols-2 gap-4">',
'            <div><label className="text-xs text-slate-400 block mb-1">Date</label>',
'              <input type="date" className={cls} value={form.date} onChange={f("date")} /></div>',
'            <div><label className="text-xs text-slate-400 block mb-1">Paid By</label>',
'              <select className={cls} value={form.paidByUserId} onChange={f("paidByUserId")}>',
'                {group.members.map((m) => <option key={m.userId} value={m.userId}>{m.name}</option>)}',
'              </select></div>',
'          </div>',
'          <div className="flex gap-3 pt-2">',
'            <button type="button" onClick={onClose} className="flex-1 py-2.5 border border-slate-200 dark:border-slate-800 text-slate-500 rounded-xl text-sm font-semibold hover:bg-slate-50 dark:hover:bg-slate-800 transition">Cancel</button>',
'            <button type="submit" className="flex-1 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-sm font-semibold shadow-md shadow-indigo-600/20 transition">Add Expense</button>',
'          </div>',
'        </form>',
'      </div>',
'    </div>',
'  );',
'};'
)

$lines | Set-Content -Path $path -Encoding UTF8
Write-Host "Part 1 written ($($lines.Count) lines)"
